CREATE TABLE IF NOT EXISTS users_group (
    id BIGINT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,
    group_name VARCHAR(255) NOT NULL,
    description TEXT DEFAULT NULL
);